//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAnswer
    {
        public int BAnswerID { get; set; }
        public int StudentExamID { get; set; }
        public System.Guid BQuestionID { get; set; }
        public string Value { get; set; }
        public Nullable<float> Rate { get; set; }
        public Nullable<int> Flags { get; set; }
    
        public virtual BQuestion BQuestion { get; set; }
        public virtual StudentExam StudentExam { get; set; }
    }
}
