//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAnswerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAnswerType()
        {
            this.BQuestions = new HashSet<BQuestion>();
        }
    
        public System.Guid ObjectID { get; set; }
        public byte MagicBit { get; set; }
        public long ts { get; set; }
        public string Name { get; set; }
        public int CharFieldType { get; set; }
        public byte Language { get; set; }
        public int CheckMode { get; set; }
        public int DictIndexRecognition { get; set; }
        public int DictIndexCheck { get; set; }
        public int DictIndexVisualCheck { get; set; }
        public string MaskNumbers { get; set; }
        public string RegExp { get; set; }
        public int CheckControlMode { get; set; }
        public string VerificationHint { get; set; }
        public int Flags { get; set; }
        public Nullable<System.Guid> OKATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BQuestion> BQuestions { get; set; }
    }
}
