//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BQuestion()
        {
            this.BAnswers = new HashSet<BAnswer>();
            this.BQuestionKeys = new HashSet<BQuestionKey>();
        }
    
        public System.Guid ObjectID { get; set; }
        public byte MagicBit { get; set; }
        public long ts { get; set; }
        public System.Guid KIM { get; set; }
        public int Number { get; set; }
        public float KeyRate { get; set; }
        public System.Guid AnswerType { get; set; }
        public int Flags { get; set; }
        public int Idcol { get; set; }
    
        public virtual BAnswerType BAnswerType { get; set; }
        public virtual KIM KIM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAnswer> BAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BQuestionKey> BQuestionKeys { get; set; }
    }
}
