//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooky
    {
        public int CookieID { get; set; }
        public int EntityId { get; set; }
        public string CookieName { get; set; }
        public string CookieValue { get; set; }
    }
}
