//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQuestion()
        {
            this.CQuestionRates = new HashSet<CQuestionRate>();
            this.CRates = new HashSet<CRate>();
        }
    
        public System.Guid ObjectID { get; set; }
        public byte MagicBit { get; set; }
        public long ts { get; set; }
        public string Rem { get; set; }
        public int Flags { get; set; }
        public int CheckMode { get; set; }
        public System.Guid KIM { get; set; }
        public int Number { get; set; }
        public int IDCol { get; set; }
    
        public virtual KIM KIM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQuestionRate> CQuestionRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRate> CRates { get; set; }
    }
}
