//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRate
    {
        public int CRateID { get; set; }
        public int StudentExamID { get; set; }
        public int ExpertID { get; set; }
        public System.Guid CQuestionID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> FinishDateTime { get; set; }
        public Nullable<float> Rate { get; set; }
        public int Flags { get; set; }
    
        public virtual CQuestion CQuestion { get; set; }
        public virtual Person Person { get; set; }
        public virtual StudentExam StudentExam { get; set; }
    }
}
