//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonateStatu
    {
        public int DonateID { get; set; }
        public System.DateTime DonateDate { get; set; }
        public byte PartOfDonate { get; set; }
        public int Total { get; set; }
        public int Flags { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int FileID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual File File { get; set; }
    }
}
