//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AISExam_testingEntities : DbContext
    {
        public AISExam_testingEntities()
            : base("name=AISExam_testingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAnswerType> BAnswerTypes { get; set; }
        public virtual DbSet<BQuestion> BQuestions { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<CQuestion> CQuestions { get; set; }
        public virtual DbSet<CQuestionRate> CQuestionRates { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<ElectronicKIM> ElectronicKIMs { get; set; }
        public virtual DbSet<ElectronicKIMTask> ElectronicKIMTasks { get; set; }
        public virtual DbSet<ElectronicKIMTaskFile> ElectronicKIMTaskFiles { get; set; }
        public virtual DbSet<KIM> KIMs { get; set; }
        public virtual DbSet<KSA> KSAs { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<BAnswer> BAnswers { get; set; }
        public virtual DbSet<BQuestionKey> BQuestionKeys { get; set; }
        public virtual DbSet<CAnswerFile> CAnswerFiles { get; set; }
        public virtual DbSet<CRate> CRates { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<DonateStatu> DonateStatus { get; set; }
        public virtual DbSet<EducationForm> EducationForms { get; set; }
        public virtual DbSet<ExamAddon> ExamAddons { get; set; }
        public virtual DbSet<ExamKim> ExamKims { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExamType> ExamTypes { get; set; }
        public virtual DbSet<FileMapping> FileMappings { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<JournalField> JournalFields { get; set; }
        public virtual DbSet<KimMedia> KimMedias { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<PersonGroup> PersonGroups { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StationExam> StationExams { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<StudentExam> StudentExams { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<DonateInfo> DonateInfoes { get; set; }
        public virtual DbSet<DonateType> DonateTypes { get; set; }
        public virtual DbSet<HistoryLog> HistoryLogs { get; set; }
        public virtual DbSet<JournalFieldValue> JournalFieldValues { get; set; }
        public virtual DbSet<LessonMaterial> LessonMaterials { get; set; }
        public virtual DbSet<LessonAddon> LessonAddons { get; set; }
        public virtual DbSet<Scale> Scales { get; set; }
        public virtual DbSet<AnketAnswer> AnketAnswers { get; set; }
        public virtual DbSet<Anket> Ankets { get; set; }
        public virtual DbSet<ObjectAnket> ObjectAnkets { get; set; }
    
        public virtual ObjectResult<ae_ekim_GetKIMStructure_Result> ae_ekim_GetKIMStructure(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ae_ekim_GetKIMStructure_Result>("ae_ekim_GetKIMStructure", idParameter);
        }
    }
}
