//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicKIMTaskFile
    {
        public System.Guid ObjectID { get; set; }
        public string Name { get; set; }
        public System.Guid ElectronicKIMTask { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.Guid> ContentType { get; set; }
        public int Flags { get; set; }
        public int IdCol { get; set; }
    
        public virtual ContentType ContentType1 { get; set; }
        public virtual ElectronicKIMTask ElectronicKIMTask1 { get; set; }
    }
}
