//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamKim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamKim()
        {
            this.BQuestionKeys = new HashSet<BQuestionKey>();
            this.ExamKims1 = new HashSet<ExamKim>();
            this.KimMedias = new HashSet<KimMedia>();
            this.StudentExams = new HashSet<StudentExam>();
        }
    
        public int ExamKimID { get; set; }
        public int ExamID { get; set; }
        public int VariantNumber { get; set; }
        public System.Guid KIM { get; set; }
        public Nullable<System.Guid> ElectronicKIMID { get; set; }
        public Nullable<int> ParentExamKimID { get; set; }
    
        public virtual ElectronicKIM ElectronicKIM { get; set; }
        public virtual KIM KIM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BQuestionKey> BQuestionKeys { get; set; }
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamKim> ExamKims1 { get; set; }
        public virtual ExamKim ExamKim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KimMedia> KimMedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExam> StudentExams { get; set; }
    }
}
