//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileMapping
    {
        public int FileMappingID { get; set; }
        public string ObjectName { get; set; }
        public int ObjectID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FriendlyDescription { get; set; }
    
        public virtual File File { get; set; }
    }
}
