//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Lessons = new HashSet<Lesson>();
            this.PersonGroups = new HashSet<PersonGroup>();
            this.DonateTypes = new HashSet<DonateType>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public int Capacity { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime FinishDateTime { get; set; }
        public int Duration { get; set; }
        public int Price { get; set; }
        public int Flags { get; set; }
        public int StationID { get; set; }
        public int EducationFormID { get; set; }
        public int CurriculumID { get; set; }
        public Nullable<byte> LessonDuration { get; set; }
        public Nullable<int> AuditoriumNumber { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual EducationForm EducationForm { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonGroup> PersonGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonateType> DonateTypes { get; set; }
    }
}
