//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalFieldValue
    {
        public int JournalFieldValueID { get; set; }
        public int JournalFieldID { get; set; }
        public int Value { get; set; }
        public int Flags { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int PersonGroupID { get; set; }
    
        public virtual JournalField JournalField { get; set; }
        public virtual PersonGroup PersonGroup { get; set; }
    }
}
