//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KimMedia
    {
        public int KimMediaID { get; set; }
        public int ExamKimID { get; set; }
        public long TaskNumberFlags { get; set; }
        public string MediaType { get; set; }
        public Nullable<int> FileID { get; set; }
    
        public virtual ExamKim ExamKim { get; set; }
        public virtual File File { get; set; }
    }
}
