//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KSA()
        {
            this.Schools = new HashSet<School>();
        }
    
        public System.Guid ObjectID { get; set; }
        public byte MagicBit { get; set; }
        public long ts { get; set; }
        public int KSAType { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<byte> Active { get; set; }
        public int Flags { get; set; }
        public string Address { get; set; }
        public string LegalAddress { get; set; }
        public string DirectorPosition { get; set; }
        public string DirectorName { get; set; }
        public string OrganizationForm { get; set; }
        public Nullable<System.Guid> School { get; set; }
        public Nullable<System.Guid> OKATO { get; set; }
        public Nullable<int> ObjectCode { get; set; }
    
        public virtual School School1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School> Schools { get; set; }
    }
}
