//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonAddon
    {
        public int LessonAddonID { get; set; }
        public Nullable<int> LessonID { get; set; }
        public string AddonShortName { get; set; }
        public string AddonDescription { get; set; }
        public string LinkAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public int Flags { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
