//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonGroup()
        {
            this.JournalFieldValues = new HashSet<JournalFieldValue>();
            this.LessonMaterials = new HashSet<LessonMaterial>();
            this.ObjectAnkets = new HashSet<ObjectAnket>();
        }
    
        public int GroupID { get; set; }
        public int PersonID { get; set; }
        public int PersonGroupID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int Flags { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EndEducationDateTime { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Order Order { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalFieldValue> JournalFieldValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonMaterial> LessonMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectAnket> ObjectAnkets { get; set; }
    }
}
