//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.CRates = new HashSet<CRate>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.PersonGroups = new HashSet<PersonGroup>();
            this.Persons1 = new HashSet<Person>();
            this.StudentExams = new HashSet<StudentExam>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int PersonID { get; set; }
        public Nullable<System.Guid> PersonGUID { get; set; }
        public int PersonTypeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string DocSeria { get; set; }
        public string DocNumber { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssedDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Phones { get; set; }
        public string Email { get; set; }
        public string RegistrationAddress { get; set; }
        public Nullable<byte> ParticipantClass { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> ParentPersonID { get; set; }
        public int Flags { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string NickName { get; set; }
        public string INN { get; set; }
        public Nullable<System.Guid> SchoolRegistration { get; set; }
        public Nullable<System.Guid> KSA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRate> CRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonGroup> PersonGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Persons1 { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual PersonType PersonType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExam> StudentExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
