//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scale
    {
        public int Id { get; set; }
        public byte Class { get; set; }
        public int SubjectID { get; set; }
        public int PrimaryMark { get; set; }
        public int TestRate { get; set; }
        public int Flags { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
