//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.KSAs = new HashSet<KSA>();
            this.School1 = new HashSet<School>();
        }
    
        public System.Guid ObjectID { get; set; }
        public byte MagicBit { get; set; }
        public long ts { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Director { get; set; }
        public string Principality { get; set; }
        public string DirectorPhone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string REM { get; set; }
        public int Flags { get; set; }
        public Nullable<int> GraduateCount { get; set; }
        public Nullable<int> UnderGraduateCount { get; set; }
        public string VUZCode { get; set; }
        public string LegalAddress { get; set; }
        public string PostAddress { get; set; }
        public string EGEResponsibleName { get; set; }
        public string URL { get; set; }
        public Nullable<System.Guid> KSA { get; set; }
        public System.Guid SchoolKind { get; set; }
        public System.Guid OKATO { get; set; }
        public Nullable<System.Guid> SchoolCenter { get; set; }
        public Nullable<System.Guid> Property { get; set; }
        public Nullable<System.Guid> Ministry { get; set; }
        public Nullable<System.Guid> ControlCenter { get; set; }
        public Nullable<System.Guid> CityType { get; set; }
        public Nullable<int> ObjectCode { get; set; }
        public string LicenseNumber { get; set; }
        public string RegisterLicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public Nullable<System.DateTime> LicenseFinishDate { get; set; }
        public string CertificateNumber { get; set; }
        public string RegisterCertificateNumber { get; set; }
        public Nullable<System.DateTime> CertificateDate { get; set; }
        public Nullable<System.DateTime> CertificateFinishDate { get; set; }
        public Nullable<System.Guid> Country { get; set; }
        public Nullable<System.Guid> DeepDiscipline { get; set; }
        public Nullable<short> PreparePrintedDocs { get; set; }
        public Nullable<short> PlanningPrintedDocs { get; set; }
        public Nullable<int> TestPointCode { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KSA> KSAs { get; set; }
        public virtual KSA KSA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School> School1 { get; set; }
        public virtual School School2 { get; set; }
    }
}
