//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentExam()
        {
            this.BAnswers = new HashSet<BAnswer>();
            this.CAnswerFiles = new HashSet<CAnswerFile>();
            this.CRates = new HashSet<CRate>();
            this.ObjectAnkets = new HashSet<ObjectAnket>();
        }
    
        public int StudentExamID { get; set; }
        public int PersonID { get; set; }
        public int ExamID { get; set; }
        public int Flags { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> StationsExamsID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<System.DateTime> FinishDateTime { get; set; }
        public Nullable<System.DateTime> PersonTestDateTime { get; set; }
        public Nullable<int> ExpertID { get; set; }
        public int CheckState { get; set; }
        public Nullable<System.Guid> ElectronicKIMID { get; set; }
        public Nullable<int> ExamKimID { get; set; }
    
        public virtual ElectronicKIM ElectronicKIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAnswer> BAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAnswerFile> CAnswerFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRate> CRates { get; set; }
        public virtual ExamKim ExamKim { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual File File { get; set; }
        public virtual Order Order { get; set; }
        public virtual Person Person { get; set; }
        public virtual StationExam StationExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectAnket> ObjectAnkets { get; set; }
    }
}
